"""One local signer with an MCP interface and the original HTTP challenge API.

Run ./start.sh, then visit http://127.0.0.1:8787 for connection instructions.
Private keys persist under private/ and are never returned by the server. No model API
is called. ChatGPT requires a separately configured tunnel to reach localhost.
"""

import argparse
import html
from pathlib import Path
import re
from urllib.parse import urlsplit

import anyio
import uvicorn
from cryptography.hazmat.primitives import serialization
from mcp.server import MCPServer
from mcp.server.transport_security import TransportSecuritySettings
from mcp.types import ToolAnnotations
from starlette.middleware.trustedhost import TrustedHostMiddleware
from starlette.responses import HTMLResponse, JSONResponse, PlainTextResponse

from local_keys import load_or_create_key
from protocol import CLAIM, MAX_MESSAGE, VERSION, decode64, fingerprint, parse_json, sign_response


def public_origin(value):
    if value is None:
        return None
    if any(character.isspace() for character in value):
        raise ValueError("--public-url must not contain whitespace")
    parsed = urlsplit(value)
    if (parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password
            or parsed.path not in {"", "/"} or parsed.query or parsed.fragment
            or "*" in parsed.netloc):
        raise ValueError("--public-url must be a concrete HTTPS origin, such as https://example.ngrok.app")
    port = parsed.port  # Accessing this validates nonnumeric and out-of-range ports.
    hostname = parsed.hostname.lower()
    if not re.fullmatch(r"[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?", hostname) or port == 0:
        raise ValueError("--public-url requires a DNS hostname or IPv4 address and a valid port")
    return "https://" + hostname + (f":{port}" if port not in {None, 443} else "")


class LocalOriginGuard:
    """Keep browser-origin protection on the custom HTTP routes as well as MCP."""

    def __init__(self, app, origins):
        self.app = app
        self.origins = origins

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            origins = [value.decode("latin-1") for key, value in scope["headers"] if key == b"origin"]
            if len(origins) > 1 or (origins and origins[0] not in self.origins):
                await PlainTextResponse("Origin is not allowed", status_code=403)(scope, receive, send)
                return
        await self.app(scope, receive, send)


def create_server(private_key, issuer, port=8787, public_url=None):
    external_origin = public_origin(public_url)
    local_url = f"http://127.0.0.1:{port}"
    public_key = private_key.public_key()
    # Validate configured issuer immediately, without publishing a response.
    sign_response(private_key, issuer, {"protocol": VERSION, "nonce": "0" * 64})
    info = {
        "protocol": VERSION,
        "issuer": issuer,
        "algorithm": "Ed25519",
        "public_key_pem": public_key.public_bytes(
            serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
        ).decode("ascii"),
        "key_fingerprint": fingerprint(public_key),
        "claim": CLAIM,
        "trust": "Discovery information only. Establish this key pin independently before verifying responses.",
        "verification": "The caller must generate and retain a fresh random nonce, then verify the signed envelope "
                        "with its pinned key, pending challenge, and elapsed-time deadline.",
        "signature_input": "UTF-8 protocol identifier, one zero byte, then base64url-decoded payload bytes",
        "signature_encoding": "padded base64url",
        "target_routing": "not_attested",
        "authorization": "not_attested",
    }
    mcp = MCPServer(
        "Live Contact", version="0.2.0",
        instructions="This service signs a caller-supplied challenge with one configured key. "
                     "Use answer_challenge with a 64-character lowercase hex nonce generated by the caller's "
                     "trusted random-number generator. A model-invented nonce is not a strong freshness test. "
                     "Verification belongs to the caller; key discovery is not independent authentication. "
                     "The result does not attest other targets' reality, routing, or authorization.",
    )

    @mcp.tool(annotations=ToolAnnotations(readOnlyHint=True, destructiveHint=False,
                                         idempotentHint=True, openWorldHint=False))
    def get_signer_info() -> dict[str, object]:
        """Get the public verification key, issuer, fingerprint, and exact claim supported by this signer."""
        return dict(info)

    @mcp.tool(annotations=ToolAnnotations(readOnlyHint=True, destructiveHint=False,
                                         idempotentHint=False, openWorldHint=False))
    def answer_challenge(nonce: str) -> dict[str, object]:
        """Sign a caller-generated nonce: exactly 64 lowercase hex characters representing 32 random bytes.

        Generate the nonce in trusted caller-side code and retain it before this
        call. Verify the returned envelope independently with the pinned key.
        Decoded fields are included for readability, not as a verification result.
        """
        envelope = sign_response(private_key, issuer, {"protocol": VERSION, "nonce": nonce})
        return {
            "envelope": envelope,
            "decoded_payload": parse_json(decode64(envelope["payload"])),
            "key_fingerprint": info["key_fingerprint"],
            "verification": "not_performed_by_signer",
            "target_routing": "not_attested",
            "authorization": "not_attested",
        }

    @mcp.custom_route("/healthz", methods=["GET"])
    async def health(request):
        return JSONResponse({"status": "ok", "protocol": VERSION})

    @mcp.custom_route("/v1/info", methods=["GET"])
    async def discovery(request):
        return JSONResponse(info, headers={"Cache-Control": "no-store"})

    @mcp.custom_route("/v1/challenge", methods=["POST"])
    async def challenge(request):
        if request.headers.get("content-type", "").split(";", 1)[0].strip() != "application/json":
            return JSONResponse({"error": "Use application/json"}, status_code=415)
        try:
            body = bytearray()
            with anyio.fail_after(5):
                async for chunk in request.stream():
                    body.extend(chunk)
                    if len(body) > MAX_MESSAGE:
                        return JSONResponse({"error": "Request too large"}, status_code=413)
            envelope = sign_response(private_key, issuer, parse_json(bytes(body)))
        except (ValueError, TimeoutError):
            return JSONResponse({"error": "Invalid or incomplete challenge"}, status_code=400)
        return JSONResponse(envelope, headers={"Cache-Control": "no-store"})

    @mcp.custom_route("/", methods=["GET"])
    async def home(request):
        escape = html.escape
        external = (f"<p>Configured public MCP URL: <code>{escape(external_origin)}/mcp</code></p>"
                    if external_origin else "")
        page = f"""<!doctype html><html lang="en"><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>Live Contact</title>
<style>body{{font:16px/1.6 system-ui;max-width:820px;margin:48px auto;padding:0 24px;color:#182230}}
code,pre{{background:#f1f4f8;border-radius:6px;padding:3px 7px;overflow-wrap:anywhere}}
pre{{padding:16px;white-space:pre-wrap}}h1{{letter-spacing:-.04em}}h2{{margin-top:32px}}
.status{{color:#166534}}a{{color:#1859ad}}</style>
<h1>Live Contact</h1><p class="status">Running locally · ready to answer challenges</p>
<p>Signer: <strong>{escape(issuer)}</strong></p>
<p>Key fingerprint: <code>{escape(info['key_fingerprint'])}</code></p>
<p><a href="/v1/info">Public key and protocol details</a> · <a href="/healthz">Health check</a></p>
<h2>Connect Codex</h2><p>Run this once, then start a new task:</p>
<pre>codex mcp add live-contact --url {escape(local_url)}/mcp</pre>
<h2>Connect ChatGPT</h2>
<p>In ChatGPT developer mode, add an MCP connection through Secure MCP Tunnel,
or use a public HTTPS tunnel pointing to this local port. The local MCP path is <code>/mcp</code>.</p>
<p>For a public tunnel, restart with <code>./start.sh --public-url https://YOUR-TUNNEL-HOST</code>
to allow its exact hostname, then add <code>https://YOUR-TUNNEL-HOST/mcp</code> in ChatGPT.</p>
{external}<p><a href="https://developers.openai.com/plugins/deploy/connect-chatgpt">ChatGPT connection instructions</a>
 · <a href="https://developers.openai.com/api/docs/guides/secure-mcp-tunnels">Secure MCP Tunnel setup</a></p>
<h2>Available tools</h2><p><code>get_signer_info()</code> discovers the public key and issuer.
<code>answer_challenge(nonce)</code> signs a fresh challenge supplied by the caller.</p>
<p>The challenge must be 64 lowercase hex characters, generated in the caller's trusted runtime.
The caller verifies the signature with an independently pinned key. This page's key listing is discovery,
not an independent trust anchor.</p>
<h2>Direct HTTP access</h2><pre>POST /v1/challenge
Content-Type: application/json

{{"protocol":"{VERSION}","nonce":"&lt;64 lowercase hex characters&gt;"}}</pre>
<p>A successful signature authenticates the signer's response. It does not establish other targets'
routing or authorize actions against them. Keep this program running while connected.</p></html>"""
        return HTMLResponse(page, headers={"Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; "
                                           "base-uri 'none'; frame-ancestors 'none'", "Cache-Control": "no-store"})

    origins = [local_url, f"http://localhost:{port}"]
    hosts = ["127.0.0.1", "localhost"]
    mcp_hosts = ["127.0.0.1:*", "localhost:*"]
    if external_origin:
        parsed = urlsplit(external_origin)
        origins.append(external_origin)
        hosts.append(parsed.hostname)
        mcp_hosts.append(parsed.netloc)
    transport_security = TransportSecuritySettings(
        enable_dns_rebinding_protection=True, allowed_hosts=mcp_hosts, allowed_origins=origins
    )
    app = mcp.streamable_http_app(json_response=True, stateless_http=True,
                                  max_request_body_size=16384, transport_security=transport_security)
    app.add_middleware(LocalOriginGuard, origins=origins)
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=hosts, www_redirect=False)
    return mcp, app


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8787)
    parser.add_argument("--issuer", default="local-research-signer")
    parser.add_argument("--key-directory", default=str(Path(__file__).parent / "private"))
    parser.add_argument("--public-url", help="optional HTTPS tunnel origin to allow; does not start a tunnel")
    args = parser.parse_args()
    if not 1 <= args.port <= 65535:
        parser.error("--port must be between 1 and 65535")
    origin = public_origin(args.public_url)
    key = load_or_create_key(args.key_directory)
    _, app = create_server(key, args.issuer, args.port, origin)
    print(f"Live Contact: http://127.0.0.1:{args.port}", flush=True)
    print(f"MCP endpoint: http://127.0.0.1:{args.port}/mcp", flush=True)
    print(f"Public key fingerprint: {fingerprint(key.public_key())}", flush=True)
    print("Open the local page for Codex and ChatGPT connection instructions. Ctrl-C stops the server.", flush=True)
    uvicorn.run(app, host="127.0.0.1", port=args.port, access_log=False,
                proxy_headers=False, log_level="warning")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError) as error:
        raise SystemExit(str(error))
